### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by IscoGamer503** [Zerthick/CommandCore#2]
Server thread/ERROR [Sponge]: Could not pass FMLInitializationEvent to Plugin{id=commandcore, name=CommandCore, version=0.2.0, description=Core Library for CommandSkript Plugins, authors=[Zerthick], source=/mods/CommandCore-v0.2.0.jar}
23.01 20:55:08 [Server] INFO java.lang.NoClassDefFoundError: io/github/zerthick/commandskript/CommandSkriptLexer
23.01 20:55:08 [Server] INFO at io.github.zerthick.commandcore.skript.Skript.<init>(Skript.java:45) ~[Skript.class:?]
23.01 20:55:08 [Server] INFO at io.github.zerthick.commandcore.CommandCore$$Lambda$593/1177297596.apply(Unknown Source) ~[?:?]

**Comment by Zerthick** [comment]
Hmmm, looks like something isn't shading properly. I'll look into this

**Comment by Zerthick** [comment]
Everything appears to be running fine when I run CommandCore-0.2.0 in the latest stable build of SpongeVanilla, what exactly are the steps to reproduce this error message?

**Comment by IscoGamer503** [comment]
I'm using forge 1.12.3 Sponge 7.0.0. Can you do a video tutorial for it? plz! or can you upload a .ck file that ejecute a looping of
"/Execute @p[score_test_min=1,score_test=1] ~ ~ ~ /tp @p <x y z>"

**Comment by Zerthick** [comment]
How exactly do you want it to loop? Once, 5 times? CommandCore isn't really designed to have scripts running continuously.

**Comment by Zerthick** [comment]
Closing due to inactivity.
